version: '3.8'

services:
    mosquitto:
      container_name: mosquitto
      image: eclipse-mosquitto:2
      volumes:
        - ./mosquitto:/mosquitto/config/:ro
      ports:
        - 1883:1883
        - 9001:9001
      networks:
        - mosquitto

networks:
    mosquitto:
        name: mosquitto
        driver: bridge